Update docker-build and mkdist

diff --git a/BuildScripts/docker-build b/BuildScripts/docker-build
--- a/BuildScripts/docker-build
+++ b/BuildScripts/docker-build
@@ -1,5 +1,10 @@
 #! /bin/sh
 
+## Perform multiple local builds using Docker
+
+## This script is part of the Talisker Developer Tools
+## https://github.com/taliskerPlatform/Developer
+
 ## Copyright 2017 Mo McRoberts.
 ##
 ##  Licensed under the Apache License, Version 2.0 (the "License");
@@ -22,36 +27,45 @@ if ! test -r configure.ac 2>&1 ; then
 	exit 1
 fi
 
-PACKAGE=$(basename `pwd` | tr A-Z a-z)
+RESOURCES="BuildResources/Docker"
+SCRIPTS="BuildScripts"
+BUILD="DockerBuild"
+BASESUFFIX="-base"
+PACKAGE=$(basename `pwd`)
+PKGNAME=""
+CACHEBUST="$$"
 
 if test -r BuildResources/Docker/docker-build.conf ; then
 	. BuildResources/Docker/docker-build.conf || exit $?
 fi
 
-SUFFIX="-base"
+test x"${PKGNAME}" = x"" && PKGNAME="`echo ${PACKAGE} | tr A-Z a-z`"
+TARBALL="${PKGNAME}-docker-root.$$.tar"
 
 function dist()
 {
-	test -d DockerBuild || mkdir -p DockerBuild
-	if ! test -r DockerBuild/${PACKAGE}-dockerroot.tar ; then
+	test -d "${BUILD}" || mkdir -p "${BUILD}" || exit $?
+	if ! test -r "${BUILD}/${TARBALL}" ; then
 		echo "Preparing source archive for Docker build..." >&2
-		BuildScripts/mkdist DockerBuild/${PACKAGE}-dockerroot.tar || exit $?
+		"${SCRIPTS}/mkdist" "${BUILD}/${TARBALL}" || exit $?
 	fi
 }
 
 function clean()
 {
-	echo "removing temporary build resources (DockerBuild)..." >&2
-	rm -rf DockerBuild
+	echo "Removing temporary build resources (DockerBuild)..." >&2
+	rm -rf "${BUILD}"
 }
 
 function update()
 {
-	subdir="$1"
-	IMAGETAG="$1"
-	IMAGENAME="${PACKAGE}${SUFFIX}:${IMAGETAG}"
-	echo "building Docker image ${IMAGENAME}..." >&2
-	docker build -t ${IMAGENAME} BuildResources/Docker/$subdir
+	local subdir="${RESOURCES}/$1"
+	local IMAGETAG="$1"
+	local IMAGENAME="${PKGNAME}${BASESUFFIX}:${IMAGETAG}"
+	local result
+	
+	echo "Building ${PACKAGE} base Docker image ${IMAGENAME}..." >&2
+	docker build -t "${IMAGENAME}" "${subdir}"
 	result=$?
 	if test $result -ne 0 ; then
 		echo "**** Docker build failed with status $result ****" >&2
@@ -61,9 +75,13 @@ function update()
 
 function prepare()
 {
-	subdir="$1"
-	printf "checking for Docker image $IMAGE-base:$subdir..." >&2
-	match="`( docker images $IMAGE-base:$subdir | egrep \"^$IMAGE-base\" ) 2>&1`"
+	local subdir="${RESOURCES}/$1"
+	local IMAGETAG="$1"
+	local IMAGENAME="${PKGNAME}${BASESUFFIX}:${IMAGETAG}"
+	local match
+	
+	printf "Checking for ${PACKAGE} base Docker image ${IMAGENAME}..." >&2
+	match="`( docker images \"${IMAGENAME}\" | egrep \"^${PKGNAME}${BASESUFFIX}\" ) 2>&1`"
 	if test x"$match" = x"" ; then
 		echo " (not found)" >&2
 		update "$subdir"
@@ -74,40 +92,84 @@ function prepare()
 
 function build()
 {
-	subdir="$1"
-	prepare "$subdir"
+	local dist="$1"
+	local target="$2"
+	local DIRNAME="${PKGNAME}-${dist}"
+	local IMAGENAME="${PKGNAME}"
+	local BASEIMAGENAME="${PKGNAME}${BASESUFFIX}:${dist}"
+	local dockerfile=""
+	local try
+	local result
+	
+	if ! test x"$target" = x"" ; then
+		IMAGENAME="${IMAGENAME}-${target}"
+		DIRNAME="${DIRNAME}-${target}"
+	fi
+	IMAGENAME="${IMAGENAME}:${dist}"
+	prepare "${dist}"
 	dist
-	printf "building $PACKAGE for $subdir...\n" >&2
-	cd DockerBuild
-	rm -rf $IMAGE-$subdir
-	mkdir $IMAGE-$subdir
-	cd $IMAGE-$subdir
-	rm -f $IMAGE-dockerroot.tar
-	cp ../$IMAGE-dockerroot.tar . 
-	cat >Dockerfile <<EOF
-## Automatically generated by BuildScripts/docker-build
+	printf "building ${PACKAGE} for ${dist}...\n" >&2
+	cd "${BUILD}"
+	rm -rf "${DIRNAME}"
+	mkdir "${DIRNAME}"
+	cd "${DIRNAME}" || return $?
+	rm -f "${TARBALL}"
+	cp "../${TARBALL}" . || return $?
+	if test x"${target}" = x"" ; then
+		try="build.tmpl"
+		suffix=""
+	else
+		try="${target}.tmpl"
+		suffix="-${target}"
+	fi
+	for dir in "${RESOURCES}/${dist}" "${RESOURCES}" ; do
+		if test -r "${dir}/${try}" ; then
+			dockerfile="${dir}/${try}"
+			echo "+ found Dockerfile template ${dockerfile}" >&2
+			break
+		fi
+	done
+	if ! test x"$dockerfile" = x"" ; then
+		sed -e "s!@PKGNAME@!${PKGNAME}!g" \
+			-e "s!@PACKAGE@!${PACKAGE}!g" \
+			-e "s!@DIST@!${dist}g" \
+			-e "s!@TARGET@!${target}!g" 
+			-e "s!@BASEIMAGENAME@!${BASEIMAGENAME}!g" \
+			-e "s!@IMAGENAME@!${IMAGENAME}!g" \
+			-e "s!@DIRNAME@!${DIRNAME}!g" \
+			-e "s!@RESOURCES@!${RESOURCES}!g" \
+			-e "s!@BUILD@!${BUILD}!g" \
+			< "$dockerfile" > Dockerfile
+	else
+		if ! test x"$target" = x"" ; then
+			echo "*** Error: could not find ${try} within ${RESOURCES}" >&2
+			return 1
+		fi
+		cat >Dockerfile <<EOF
+## Automatically generated by ${SCRIPTS}/docker-build
 
-FROM $IMAGE-base:$subdir
+FROM ${BASEIMAGENAME}
 
-RUN mkdir -p /root/BuildRoot/$PACKAGE
+RUN mkdir -p /root/BuildRoot/${PKGNAME}
 
-ADD $IMAGE-dockerroot.tar /root/BuildRoot/$PACKAGE
+ADD ${TARBALL} /root/BuildRoot/${PKGNAME}
 
 WORKDIR /root/BuildRoot
 
 RUN cd /root/BuildRoot && \
-	$PACKAGE/BuildResources/CI/before_install.sh
+	${PKGNAME}/BuildResources/CI/before_install.sh "$dist" "$target"
 
-RUN cd /root/BuildRoot/$PACKAGE && \
+RUN cd /root/BuildRoot/${PKGNAME} && \
 	autoreconf -fvi && \
 	./configure
 
-RUN cd /root/BuildRoot/$PACKAGE && make clean
-RUN cd /root/BuildRoot/$PACKAGE && make all
-RUN cd /root/BuildRoot/$PACKAGE && make check
-RUN cd /root/BuildRoot/$PACKAGE && make install
+RUN cd /root/BuildRoot/${PKGNAME} && make clean
+RUN cd /root/BuildRoot/${PKGNAME} && make all
+RUN cd /root/BuildRoot/${PKGNAME} && make check
+RUN cd /root/BuildRoot/${PKGNAME} && make install
 EOF
-	docker build -t $IMAGE:$subdir .
+	fi
+	docker build --no-cache -t "${IMAGENAME}" .
 	result=$?
 	if test $result -ne 0 ; then
 		echo "**** Docker build failed with status $result ****" >&2
@@ -120,7 +182,7 @@ EOF
 function build_one()
 {
 	clean
-	build "$1"
+	build "$1" "$2"
 	result=$?
 	clean
 	exit $?
@@ -128,6 +190,8 @@ function build_one()
 
 function list()
 {
+	local subdir
+	
 	for subdir in `cd BuildResources/Docker && echo *` ; do
 		if test -r "BuildResources/Docker/$subdir/Dockerfile" ; then
 			echo "  $subdir"
@@ -138,6 +202,8 @@ function list()
 
 function update_all()
 {
+	local subdir
+	
 	for subdir in `cd BuildResources/Docker && echo *` ; do
 		if test -r "BuildResources/Docker/$subdir/Dockerfile" ; then
 			update "$subdir"
@@ -156,11 +222,15 @@ function prepare_all()
 
 function build_all()
 {
+	local target="$1"
+	local result
+	local subdir
+	
 	clean
 	result=0
 	for subdir in `cd BuildResources/Docker && echo *` ; do
 		if test -r "BuildResources/Docker/$subdir/Dockerfile" ; then
-			build "$subdir"
+			build "$subdir" "$target"
 			result=$?
 			if test $result -ne 0 ; then
 				break
@@ -196,7 +266,7 @@ fi
 case "$1" in
 	all)
 		clean
-		build_all
+		build_all "$2"
 		;;
 	clean)
 		clean
@@ -220,7 +290,7 @@ case "$1" in
 		;;
 	*)
 		if test -r "BuildResources/Docker/$1/Dockerfile" ; then
-			build_one "$1"
+			build_one "$1" "$2"
 		else
 			usage
 		fi
